[package]
name = "storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
protobuf = { version = "2.8.2", features = ["with-bytes"] }
grpc = "0.6.2"
