// This file is generated by rust-protobuf 2.8.2. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `proto/configuration/builder/builder.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_8_2;

#[derive(PartialEq,Clone,Default)]
pub struct SchedulerConfiguration {
    // message fields
    pub endpoint: ::protobuf::SingularPtrField<super::grpc::ClientConfiguration>,
    pub add_instance_name_prefix: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SchedulerConfiguration {
    fn default() -> &'a SchedulerConfiguration {
        <SchedulerConfiguration as ::protobuf::Message>::default_instance()
    }
}

impl SchedulerConfiguration {
    pub fn new() -> SchedulerConfiguration {
        ::std::default::Default::default()
    }

    // .grpc.ClientConfiguration endpoint = 1;


    pub fn get_endpoint(&self) -> &super::grpc::ClientConfiguration {
        self.endpoint.as_ref().unwrap_or_else(|| super::grpc::ClientConfiguration::default_instance())
    }
    pub fn clear_endpoint(&mut self) {
        self.endpoint.clear();
    }

    pub fn has_endpoint(&self) -> bool {
        self.endpoint.is_some()
    }

    // Param is passed by value, moved
    pub fn set_endpoint(&mut self, v: super::grpc::ClientConfiguration) {
        self.endpoint = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_endpoint(&mut self) -> &mut super::grpc::ClientConfiguration {
        if self.endpoint.is_none() {
            self.endpoint.set_default();
        }
        self.endpoint.as_mut().unwrap()
    }

    // Take field
    pub fn take_endpoint(&mut self) -> super::grpc::ClientConfiguration {
        self.endpoint.take().unwrap_or_else(|| super::grpc::ClientConfiguration::new())
    }

    // string add_instance_name_prefix = 2;


    pub fn get_add_instance_name_prefix(&self) -> &str {
        &self.add_instance_name_prefix
    }
    pub fn clear_add_instance_name_prefix(&mut self) {
        self.add_instance_name_prefix.clear();
    }

    // Param is passed by value, moved
    pub fn set_add_instance_name_prefix(&mut self, v: ::std::string::String) {
        self.add_instance_name_prefix = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_add_instance_name_prefix(&mut self) -> &mut ::std::string::String {
        &mut self.add_instance_name_prefix
    }

    // Take field
    pub fn take_add_instance_name_prefix(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.add_instance_name_prefix, ::std::string::String::new())
    }
}

impl ::protobuf::Message for SchedulerConfiguration {
    fn is_initialized(&self) -> bool {
        for v in &self.endpoint {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.endpoint)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.add_instance_name_prefix)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.endpoint.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if !self.add_instance_name_prefix.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.add_instance_name_prefix);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.endpoint.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if !self.add_instance_name_prefix.is_empty() {
            os.write_string(2, &self.add_instance_name_prefix)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SchedulerConfiguration {
        SchedulerConfiguration::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::grpc::ClientConfiguration>>(
                    "endpoint",
                    |m: &SchedulerConfiguration| { &m.endpoint },
                    |m: &mut SchedulerConfiguration| { &mut m.endpoint },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "add_instance_name_prefix",
                    |m: &SchedulerConfiguration| { &m.add_instance_name_prefix },
                    |m: &mut SchedulerConfiguration| { &mut m.add_instance_name_prefix },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<SchedulerConfiguration>(
                    "SchedulerConfiguration",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static SchedulerConfiguration {
        static mut instance: ::protobuf::lazy::Lazy<SchedulerConfiguration> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const SchedulerConfiguration,
        };
        unsafe {
            instance.get(SchedulerConfiguration::new)
        }
    }
}

impl ::protobuf::Clear for SchedulerConfiguration {
    fn clear(&mut self) {
        self.endpoint.clear();
        self.add_instance_name_prefix.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SchedulerConfiguration {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SchedulerConfiguration {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n)proto/configuration/builder/builder.proto\x12\x07builder\x1a#proto/co\
    nfiguration/grpc/grpc.proto\"\x88\x01\n\x16SchedulerConfiguration\x125\n\
    \x08endpoint\x18\x01\x20\x01(\x0b2\x19.grpc.ClientConfigurationR\x08endp\
    oint\x127\n\x18add_instance_name_prefix\x18\x02\x20\x01(\tR\x15addInstan\
    ceNamePrefixb\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
