// This file is generated by rust-protobuf 2.8.2. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `proto/configuration/http/http.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_8_2;

#[derive(PartialEq,Clone,Default)]
pub struct ClientConfiguration {
    // message fields
    pub tls: ::protobuf::SingularPtrField<super::tls::ClientConfiguration>,
    pub proxy_url: ::std::string::String,
    pub add_headers: ::protobuf::RepeatedField<ClientConfiguration_HeaderValues>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ClientConfiguration {
    fn default() -> &'a ClientConfiguration {
        <ClientConfiguration as ::protobuf::Message>::default_instance()
    }
}

impl ClientConfiguration {
    pub fn new() -> ClientConfiguration {
        ::std::default::Default::default()
    }

    // .tls.ClientConfiguration tls = 1;


    pub fn get_tls(&self) -> &super::tls::ClientConfiguration {
        self.tls.as_ref().unwrap_or_else(|| super::tls::ClientConfiguration::default_instance())
    }
    pub fn clear_tls(&mut self) {
        self.tls.clear();
    }

    pub fn has_tls(&self) -> bool {
        self.tls.is_some()
    }

    // Param is passed by value, moved
    pub fn set_tls(&mut self, v: super::tls::ClientConfiguration) {
        self.tls = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_tls(&mut self) -> &mut super::tls::ClientConfiguration {
        if self.tls.is_none() {
            self.tls.set_default();
        }
        self.tls.as_mut().unwrap()
    }

    // Take field
    pub fn take_tls(&mut self) -> super::tls::ClientConfiguration {
        self.tls.take().unwrap_or_else(|| super::tls::ClientConfiguration::new())
    }

    // string proxy_url = 2;


    pub fn get_proxy_url(&self) -> &str {
        &self.proxy_url
    }
    pub fn clear_proxy_url(&mut self) {
        self.proxy_url.clear();
    }

    // Param is passed by value, moved
    pub fn set_proxy_url(&mut self, v: ::std::string::String) {
        self.proxy_url = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_proxy_url(&mut self) -> &mut ::std::string::String {
        &mut self.proxy_url
    }

    // Take field
    pub fn take_proxy_url(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.proxy_url, ::std::string::String::new())
    }

    // repeated .http.ClientConfiguration.HeaderValues add_headers = 5;


    pub fn get_add_headers(&self) -> &[ClientConfiguration_HeaderValues] {
        &self.add_headers
    }
    pub fn clear_add_headers(&mut self) {
        self.add_headers.clear();
    }

    // Param is passed by value, moved
    pub fn set_add_headers(&mut self, v: ::protobuf::RepeatedField<ClientConfiguration_HeaderValues>) {
        self.add_headers = v;
    }

    // Mutable pointer to the field.
    pub fn mut_add_headers(&mut self) -> &mut ::protobuf::RepeatedField<ClientConfiguration_HeaderValues> {
        &mut self.add_headers
    }

    // Take field
    pub fn take_add_headers(&mut self) -> ::protobuf::RepeatedField<ClientConfiguration_HeaderValues> {
        ::std::mem::replace(&mut self.add_headers, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for ClientConfiguration {
    fn is_initialized(&self) -> bool {
        for v in &self.tls {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.add_headers {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.tls)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.proxy_url)?;
                },
                5 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.add_headers)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.tls.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if !self.proxy_url.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.proxy_url);
        }
        for value in &self.add_headers {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.tls.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if !self.proxy_url.is_empty() {
            os.write_string(2, &self.proxy_url)?;
        }
        for v in &self.add_headers {
            os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ClientConfiguration {
        ClientConfiguration::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::tls::ClientConfiguration>>(
                    "tls",
                    |m: &ClientConfiguration| { &m.tls },
                    |m: &mut ClientConfiguration| { &mut m.tls },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "proxy_url",
                    |m: &ClientConfiguration| { &m.proxy_url },
                    |m: &mut ClientConfiguration| { &mut m.proxy_url },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ClientConfiguration_HeaderValues>>(
                    "add_headers",
                    |m: &ClientConfiguration| { &m.add_headers },
                    |m: &mut ClientConfiguration| { &mut m.add_headers },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ClientConfiguration>(
                    "ClientConfiguration",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ClientConfiguration {
        static mut instance: ::protobuf::lazy::Lazy<ClientConfiguration> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ClientConfiguration,
        };
        unsafe {
            instance.get(ClientConfiguration::new)
        }
    }
}

impl ::protobuf::Clear for ClientConfiguration {
    fn clear(&mut self) {
        self.tls.clear();
        self.proxy_url.clear();
        self.add_headers.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ClientConfiguration {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ClientConfiguration {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ClientConfiguration_HeaderValues {
    // message fields
    pub header: ::std::string::String,
    pub values: ::protobuf::RepeatedField<::std::string::String>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ClientConfiguration_HeaderValues {
    fn default() -> &'a ClientConfiguration_HeaderValues {
        <ClientConfiguration_HeaderValues as ::protobuf::Message>::default_instance()
    }
}

impl ClientConfiguration_HeaderValues {
    pub fn new() -> ClientConfiguration_HeaderValues {
        ::std::default::Default::default()
    }

    // string header = 1;


    pub fn get_header(&self) -> &str {
        &self.header
    }
    pub fn clear_header(&mut self) {
        self.header.clear();
    }

    // Param is passed by value, moved
    pub fn set_header(&mut self, v: ::std::string::String) {
        self.header = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_header(&mut self) -> &mut ::std::string::String {
        &mut self.header
    }

    // Take field
    pub fn take_header(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.header, ::std::string::String::new())
    }

    // repeated string values = 2;


    pub fn get_values(&self) -> &[::std::string::String] {
        &self.values
    }
    pub fn clear_values(&mut self) {
        self.values.clear();
    }

    // Param is passed by value, moved
    pub fn set_values(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.values = v;
    }

    // Mutable pointer to the field.
    pub fn mut_values(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.values
    }

    // Take field
    pub fn take_values(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.values, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for ClientConfiguration_HeaderValues {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.header)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.values)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.header.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.header);
        }
        for value in &self.values {
            my_size += ::protobuf::rt::string_size(2, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.header.is_empty() {
            os.write_string(1, &self.header)?;
        }
        for v in &self.values {
            os.write_string(2, &v)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ClientConfiguration_HeaderValues {
        ClientConfiguration_HeaderValues::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "header",
                    |m: &ClientConfiguration_HeaderValues| { &m.header },
                    |m: &mut ClientConfiguration_HeaderValues| { &mut m.header },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "values",
                    |m: &ClientConfiguration_HeaderValues| { &m.values },
                    |m: &mut ClientConfiguration_HeaderValues| { &mut m.values },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ClientConfiguration_HeaderValues>(
                    "ClientConfiguration_HeaderValues",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ClientConfiguration_HeaderValues {
        static mut instance: ::protobuf::lazy::Lazy<ClientConfiguration_HeaderValues> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ClientConfiguration_HeaderValues,
        };
        unsafe {
            instance.get(ClientConfiguration_HeaderValues::new)
        }
    }
}

impl ::protobuf::Clear for ClientConfiguration_HeaderValues {
    fn clear(&mut self) {
        self.header.clear();
        self.values.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ClientConfiguration_HeaderValues {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ClientConfiguration_HeaderValues {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n#proto/configuration/http/http.proto\x12\x04http\x1a!proto/configurati\
    on/tls/tls.proto\"\xe7\x01\n\x13ClientConfiguration\x12*\n\x03tls\x18\
    \x01\x20\x01(\x0b2\x18.tls.ClientConfigurationR\x03tls\x12\x1b\n\tproxy_\
    url\x18\x02\x20\x01(\tR\x08proxyUrl\x12G\n\x0badd_headers\x18\x05\x20\
    \x03(\x0b2&.http.ClientConfiguration.HeaderValuesR\naddHeaders\x1a>\n\
    \x0cHeaderValues\x12\x16\n\x06header\x18\x01\x20\x01(\tR\x06header\x12\
    \x16\n\x06values\x18\x02\x20\x03(\tR\x06valuesb\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
